### ISSUE TITLE
The module could find the model

### ISSUE THREAD

**Issue by l7410559** [Magisk-Modules-Repo/NfcScreenOff#7]
![Screenshot_2020-06-09-22-47-33-75](https://user-images.githubusercontent.com/17084369/84164054-af434000-aaa4-11ea-9024-36a74d89a2dd.jpg)
Thank for your work. But I can not install this module.
From the code, maybe because of the file can not know my model, so it will not give me the file to replace.
My phone is oppo reno ace, cpu is 855+,maybe because this model is only selled in China.

**Comment by lapwat** [comment]
Thank you for the feedback.

Can you please upload those files so I can see what's going on:
- /system/app/NQfcNci/NQfcNci.apk
- /system/framework/framework-res.apk

**Comment by l7410559** [comment]
There is the link of file. Thank a million.

**Comment by lapwat** [comment]
I don't see the link, can you share it?

**Comment by l7410559** [comment]
Sorry, I am not familiar with this website.
This is the file link.
https://mega.nz/folder/PFMFGCBL#XXRLZIY1460sZhr5qtjstQ

**Comment by lapwat** [comment]
The issue was that your files where disassembled inside `smali_classes2` folder instead of `smali` folder.

I have updated the server with a new version. Please try reinstalling the module. If it works, feel free to close this issue.

Thank you very much for the feedback, it helped improve the module for you and future users that may bump into this issue :)

**Comment by l7410559** [comment]
Thank a million. It works now.
